#!/bin/bash

echo $@ | grep  -e '\-\-dry-run' -e '\-\-help' -e '\-h' 2>&1 >/dev/null
is_recorded=$? # 0 (grep successful) no, 1 (grep failed) yes

dir=$(dirname $(readlink -f $0))

if [ ${is_recorded} -eq 0 ]
then
    echo "No log is taken"
    python3 ${dir}/process_commissioning_data.py $@
    
else
    log=/home/inttdev/INTT/log/inttdaq_cron/`date +\%Y\%m\%d_\%H\%M\%S\%N`.log
    #log=/Users/genki/INTT/log/process_data/`date +\%Y\%m\%d_\%H\%M\%S\%3`.log
    echo -e "\nLog file: ${log}\n"
    
    python3 ${dir}/process_commissioning_data.py $@ 2>&1 | tee $log
    echo -e "\n\nLog file: ${log}"

    echo $@ | grep '\-\-check-bbox'  2>&1 >/dev/null
    is_checked=$? # 0 (grep successful) no, 1 (grep failed) yes
    if [ ${is_checked} -eq 0 ]
    then
	grep "Sending run" $log
    fi
    
fi
