Universe           = vanilla
Initialdir         = /sphenix/user/ChengWei/INTT/INTT/general_codes/CWShih/INTTHitMapEvt/macro_HLSpecified
Executable         = run_job.sh
PeriodicHold       = (NumJobStarts>=1 && JobStatus == 1)
concurrency_limits = CONCURRENCY_LIMIT_DEFAULT:100
request_memory     = 4GB
Priority           = 20
job_lease_duration = 86400

runnumber          = 54280
nEvents            = -1
input_directory    = /sphenix/lustre01/sphnxpro/physics/slurp/streaming/physics/ana441_2024p007/run_00054200_00054300
job_offset    = 0
process_shift      = $(Process) + $(job_offset) 
input_filename     = DST_INTT_EVENT_run2auau_ana441_2024p007-$INT(runnumber,%08d)-$INT(process_shift,%05d).root
output_directory   = /sphenix/user/ChengWei/Data_temp/run_54280/ChipOccupancy_Trig30cm/completed/CheckSaturated_HL
input_checkHL_file = /sphenix/user/ChengWei/Data_temp/run_54280/ChipOccupancy_Trig30cm/completed/ChipOccupancy_HitQA_CloneHitRemovedBCO_MBDNSTrigvtxZ30cm_00054280_$INT(process_shift,%05d).root

Output             = $(output_directory)/cw_log/condor_$INT(process_shift,%05d).out
Error              = $(output_directory)/cw_log/condor_$INT(process_shift,%05d).err
Log                = $(output_directory)/cw_log/condor_$INT(process_shift,%05d).log
Arguments          = "$INT(process_shift) $(runnumber) $(nEvents) $(output_directory) $(input_directory) $(input_filename) $(input_checkHL_file)"
Queue 300