Universe	= vanilla
Executable	= /sphenix/u/jbertaux/sphnx_software/INTT/general_codes/josephb/codes/channel_classifier/channel_classify.sh
Arguments	= 20446
notification	= Never

Output		= /sphenix/u/jbertaux/sphnx_software/INTT/general_codes/josephb/codes/channel_classifier/out/out_20446.txt
Error		= /sphenix/u/jbertaux/sphnx_software/INTT/general_codes/josephb/codes/channel_classifier/err/err_20446.txt
Log		= /tmp/condor$(process)_jbertaux.log

Initialdir	= /sphenix/u/jbertaux/sphnx_software/INTT/general_codes/josephb/codes/channel_classifier
request_memory	= 4096MB
PeriodicHold	= (NumJobStarts >= 1 && JobStatus == 1)

Queue

